
import {
    AppWindow,
    Bot,
    Puzzle,
    Wallet,
    FileJson,
    Network,
    BotMessageSquare,
    AreaChart,
    FileArchive,
    ShieldCheck,
    Vote,
    Sprout,
    Wrench,
    BookOpen,
    Download,
    Terminal,
    Code2,
    Newspaper,
    Check,
    BrainCircuit,
    SlidersHorizontal,
    Wind,
    Wand2,
    ChevronsRight,
    Plus,
    X,
  } from 'lucide-react';
  import type { LucideIcon } from 'lucide-react';

  export const iconMap: Record<string, LucideIcon> = {
    AppWindow,
    Bot,
    Puzzle,
    Wallet,
    FileJson,
    Network,
    BotMessageSquare,
    AreaChart,
    FileArchive,
    ShieldCheck,
    Vote,
    Sprout,
    Wrench,
    BookOpen,
    Download,
    Terminal,
    Code2,
    Newspaper,
    Check,
    BrainCircuit,
    SlidersHorizontal,
    Wind,
    Wand2,
    ChevronsRight,
    Plus,
    X,
  };
